### ISSUE TITLE
open source the code 

### ISSUE THREAD

**Issue by KerryZack** [Junjie-Ye/ToolSword#1]
Hello, I am very interested in your work. When do you plan to open source the related code?

**Comment by Junjie-Ye** [comment]
Hi, our data has been open-sourced, and the code is the official inference code for each model, so you can just use the inference code for the corresponding model to do the inference.

Please note that you need to convert the data into the form of tool call data organization officially specified by the corresponding model.

**Comment by KerryZack** [comment]
OK, I understand now, thank you for your help
